### ISSUE TITLE
please have an option to have it auto-generate 

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [FallenMax/smart-toc#1]
1 less shortcut makes life a tiny bit easier

best content list currently though =)

if it could always show on the left side instead of right/left seemingly randomly, that would be great since sometimes on the right side the titles are too long and overflows and breaks the content list

**Comment by FallenMax** [comment]
@SolveAllProblemsRightNow Sorry for seeing this late and thank you for suggestions :) 

For Auto-Generating TOC, if this option is provided and enabled:
1. it will show "No headings detected" toast on 90% web pages where it didn't find headings, and get annoying quickly
2. for some pages it will keep showing wrong TOC, as it's, sadly, not that smart to always get it right :(  
3. it now runs on every page, eating unnecessary CPU/memory, and make it less lovable
So I think these problem overweights benefits of saving some key strokes :P  
(but maybe we could make it remember pages that user toggled it on, and then automatically toggle it on for later visits?) 

For TOC positioning issue: 
Smart TOC uses a simple/naive algorithm to decide "best" side to place TOC (so user don't have to):
"which side has more free space? --> just put it there!" 
I observed that most of the time this kinda works. Could you show the specific URL where it doesn't work well (if it's not sensitive)? Let me see what I can do to improve this algorithm. 

Also, did you have SmartTOC upgraded to the latest version (0.3.9)? In recent versions, titles should not overflow. If they are too long, they will display with ellipsis, and be fully expanded only when you hover on TOC. Please take a look if that's the case.

I'm glad this extension is useful to you, Please feel free to raise further issue/suggestions.

**Comment by SolveAllProblemsRightNow** [comment]
**why this problem exist --**

* cos 99% of sites are extremely bad designed 
* and do not include their own 'outline' or 'overlay on the side'
* so this extension corrects for it

**what's the key problem here --**

* i often forget to use it cos the extension doesn't auto

**where the 'overflow' problem happens --**

* im sure it happens in many places, just right now i can examples of:
* https://www.omnigroup.com/blog/looking-back-looking-ahead-2017-edition
* https://github.com/brookhong/Surfingkeys#edit-your-own-settings

**potential solutions --**

* if the extension had ML, and could auto on the right pages

**version --**

* since extensions auto-update, im guessing the extensions are always on the most recent versions

**else --**

* are you at a university? if so, which one?
