### ISSUE TITLE
Any plan to support Firefox?

### ISSUE THREAD

**Issue by alswl** [FallenMax/smart-toc#10]
Firefox supported WebExtension, do you have any plan to support Firefox?

Thanks.

**Comment by FallenMax** [comment]
@alswl Thanks, will look into it.

**Comment by FallenMax** [comment]
Thanks to @alswl 's help, it's now submitted to Firefox store and under review: https://addons.mozilla.org/en-US/firefox/addon/smart_toc/ (should be available once review is passed)

Relevant commit: 3616d7876ae8ed221fbc6676fa10fdb92376665d

**Comment by alswl** [comment]
Now it's available! 🎉
