### ISSUE TITLE
shortcuts does not work

### ISSUE THREAD

**Issue by AhianZhang** [FallenMax/smart-toc#13]
env: 
- macOS Catalina 10.15.7
- chrome 86

`Command+Shift+E` cannot toggle toc

**Comment by FallenMax** [comment]
@AhianZhang  Can you check Shortcut Settings page ([chrome://extensions/shortcuts]), and see if `Show/hide TOC` has corresponding shortcut binding?

**Comment by AhianZhang** [comment]
According to your prompt, I found that the configuration is empty, and then I added a shortcut key and it took effect
