### ISSUE TITLE
opens within bounds of window 

### ISSUE THREAD

**Issue by makethingsbetter** [FallenMax/smart-toc#15]
sometimes it opens and passes the edges of the screen/window

please make it opens within the bounds/confines of window/chrome

may be more of a challenge than making it auto-generate 

auto-generate is much much more important

---

over time a bit more sites has an always-on-top outline but it's very slow progress
and this is still a huge web/societal problem

**Comment by FallenMax** [comment]
Planned in next major release.

**Comment by FallenMax** [comment]
1. The `out-of-viewport` issue is fixed.
2. Auto-generate feature is under consideration.
