### ISSUE TITLE
Impact webpage's layout

### ISSUE THREAD

**Issue by yantaozhao** [FallenMax/smart-toc#17]
When use smart-toc on some websites, it may change the webpage's layout when calling out the TOC, which is unexpected.
E.g.: [wikipedia.org](https://en.wikipedia.org/wiki/Main_Page)

**Comment by FallenMax** [comment]
@yantaozhao Thanks, I know it may look surprising, but it's actually an intended behavior. This plugin is developed to improve readability of web articles, and I found that improper line width (i.e. too many characters per line) is a really common typography issue that I can't stand. So I introduced this "max-width" rule in Smart TOC.

And, this behavior is originally developed to fix Wikipedia. 😏
