### ISSUE TITLE
Hope that night mode can be added

### ISSUE THREAD

**Issue by gitbai-ster** [FallenMax/smart-toc#18]
Hope that night mode can be added

![图片](https://user-images.githubusercontent.com/63347530/144730770-c245b43b-a1f5-46f9-b3de-1628c0245938.png)

**Comment by FallenMax** [comment]
Will be added, but it might be behind paid version (not sure yet) :)

**Comment by BoyanXu** [comment]
Hi @FallenMax , I added dark-mode feature in #20 

This use `@media (prefers-color-scheme: light/dark)` feature to make the decision on when to use dark mode  (see: [this page](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme))

This is how it looks like:

<img width="1496" alt="图片" src="https://user-images.githubusercontent.com/34408790/157523224-951c46cb-4c28-4438-a107-95211be0f2cf.png">

**Comment by FallenMax** [comment]
Dark mode is now add in Pro version, closing now :)
