### ISSUE TITLE
Breaking Change: i modified the smart-toc code to support inoreader and feedly

### ISSUE THREAD

**Issue by lcomplete** [FallenMax/smart-toc#19]
I modified the smart-toc code to support inoreader and feedly, and fix some bug, but i made some breaking changes, so i doesn't make a pr, i think maybe we can discuss more detail, if the project is continue, you can find the contact way on my github profile page.

by the way, i'm a chinese developer.

谢谢。

**Comment by BoyanXu** [comment]
Hi @lcomplete , I added dark-mode feature in https://github.com/FallenMax/smart-toc/pull/20

This includes a simple css tweak using @media (prefers-color-scheme: light/dark) feature to make the decision on when to use dark mode (see: [this page](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme))

This is how it looks like:
<img width="1496" alt="157523224-951c46cb-4c28-4438-a107-95211be0f2cf" src="https://user-images.githubusercontent.com/34408790/158011697-ad211e2f-7c41-488c-b97f-20078f66c247.png">

I don't have time to make another PR recently. If you are available, may you have a check on how to integrate this feature? This original repo seems to have been inactive for a while

**Comment by lcomplete** [comment]
Check my fork repo https://github.com/lcomplete/smart-toc ,  i had upgrade the extension manifest to v3, and add options page, so add the dark mode as an option will be good.

I'll do the code lately, thank you for the pull request.
