### ISSUE TITLE
Update for Firefox needed

### ISSUE THREAD

**Issue by Jiang10086** [FallenMax/smart-toc#29]
@Jiang10086  It's already added in Pro version, please take a look (and hope it's understandable 🥲 at least...)

_Originally posted by @FallenMax in https://github.com/FallenMax/smart-toc/issues/28#issuecomment-1202263653_

I mean the Firefox version, please update it to the newer version

**Comment by FallenMax** [comment]
@Jiang10086  Thank you, tracking FireFox porting with #31 now
