### ISSUE TITLE
Pro version for Firefox

### ISSUE THREAD

**Issue by andrewrproper** [FallenMax/smart-toc#31]
I would like to use dark mode. I'm happy to pay for it. But I would like to use it in Firefox. Is this possible, or planned?

**Comment by FallenMax** [comment]
@andrewrproper Thank you! SmartTOC for Firefox and other non-chromium browser version (Vivaldi/Brave/Opera) is being worked on and have some progress. Two problems are to be resolved:

1. Distribute as "Manifest V2" as FireFox requires, this is partially done.
2. Figure out alternative user authorizing method, browser account API (`identity.email`) is not supported in FireFox and other browsers), this still need some work.

**Comment by FallenMax** [comment]
@andrewrproper 

Hello, the FireFox version of the extension has been updated and now includes Pro version features, as well as the ability to log in using Email + Code. Please visit https://addons.mozilla.org/en-US/firefox/addon/smart_toc/ to download.

**Comment by andrewrproper** [comment]
@FallenMax great, thank you!
