### ISSUE TITLE
The source code seems to be outdated?

### ISSUE THREAD

**Issue by brlin-tw** [FallenMax/smart-toc#36]
Not that I object to proprietary software or anything, but the source code doesn't seem to be in sync with the version published on the store, judging from the Git history and the addon update date.

Could you mention the actual licensing state directly in the project README so the users won't be confused?

**Comment by FallenMax** [comment]
Thanks for spotting this. I agree and this should be made clear. I've updated the readme.

Hope to tidy up the code a bit and make the "non-Pro" part of it open if I got some spare time.
