### ISSUE TITLE
 doesn't work correctly for spring reference page

### ISSUE THREAD

**Issue by qiaoxingxing** [FallenMax/smart-toc#5]
It doesn't work correctly for these sites:

https://docs.spring.io/spring-boot/docs/2.1.0.BUILD-SNAPSHOT/reference/htmlsingle/
https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/htmlsingle/#preface

**Comment by FallenMax** [comment]
solved with 20f593fc67b1f07c5108b450d9e1afbdef0368ff
