### ISSUE TITLE
TOC disappears while widening browser window

### ISSUE THREAD

**Issue by kurtontheway** [FallenMax/smart-toc#7]
Hi
I have to say smart-toc is the best toc extension I've ever found in chrome web store, It's simple and well-designed although there is a little problem every time when i resize the browser, see the follow GIF..
![Smart TOC issue resizing browser](https://user-images.githubusercontent.com/2269311/55398680-be169480-557b-11e9-9487-70712afc7c90.gif)
[Web page shown in the above GIF](https://developer.shotgunsoftware.com/toolkit/learning-resources/guides/advanced_config/#extending-the-default-configuration)
Smart Toc version: 0.5.4
Chrome version: 74.0.3729.40 beta 64bit）
on Windows 10 1809

**Comment by FallenMax** [comment]
@kurtontheway Thank you for detailed reporting ! It's fixed in 0.5.5.

The problem was caused by SmartTOC panel re-adjusting its placement (left/right to the article) whenever window is resized. Since 0.5.5, it will only calculate placement on initial render.
